spring.application.name=M8_API_GateWay
spring.cloud.gateway.server.webflux.routes[0].id=api-1
spring.cloud.gateway.server.webflux.routes[0].uri=lb\://M9-A
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path\=/pro
spring.cloud.gateway.server.webflux.routes[1].id=api-2
spring.cloud.gateway.server.webflux.routes[1].uri=lb\://M9-B
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path\=/info
server.port=45455
