spring:
  application:
    name: Kafka_4
  kafka:
    bootstrap-servers:
    - localhost:11000
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: 'com.isrdc.models'
        spring.json.value.default.type: 'com.isrdc.models.Student'
      
server.port: 9091
topic:
  name: TopicA
  partition: 2