spring:
  application:
    name: r26
  datasource:
    url: jdbc:mysql://localhost:3306/schooldb
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql:   true
server:
  port: 9090