spring:
  application:
    name: M14_Circuit-Breaker
server:
  port: 9090
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
resilience4j:
  circuitbreaker:
   configs:
     default: 
       registerHealthIndicator: true
       slidingWindowSize: 10
       minimumNumberOfCalls: 5
       permittedNumberOfCallsInHalfOpenState: 3
       automaticTransitionFromOpenToHalfOpenEnabled: true
       waitDurationInOpenState: 100s
       failureRateThreshold: 5			


       