spring:
  application:
    name: M9-API-gateway
  cloud:
    gateway:
     server:
       webflux:
          routes:
          - id: api-1
            uri: lb://M9-A
            predicates:
            - Path=/pro
          - id: api-2
            uri: lb://M9-B
            predicates:
            - Path=/info
server:
  port: 45455
