spring:
  application:
    name: S-6-JWT
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/s7jwtdb
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 9090