spring.application.name=P24
server.port=8888
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:tmpdb
spring.datasource.username=yamraj
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.h2.console.enabled=true